server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/evgeniiruchko/shop-config
          default-label: main
          username: #login
          password: #password
          clone-on-start: true
#        native:
#          search-locations: classpath:/config

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
